/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class Library {
    public void printGreeting() {
        System.out.println("Hello from Matt's library!");
    }
}
