/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;

public class LibraryTest {
    @Test public void testPrintGreeting() {
        Library classUnderTest = new Library();
        classUnderTest.printGreeting();
    }
}
